version: "3.8"

services:
    airflow_postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        build:
            context: docker/airflow
            dockerfile: Dockerfile
        restart: always
        command: sh -c "./start.sh && airflow webserver"
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        depends_on:
            - airflow_postgres

    scheduler:
        build:
            context: docker/airflow
            dockerfile: Dockerfile
        restart: always
        command: sh -c "./start.sh && airflow scheduler"
        volumes:
            - ./dags:/usr/local/airflow/dags
        depends_on:
            - airflow_postgres